# Generated by Django 4.1.7 on 2023-03-02 19:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='О нас РУС')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='О нас УЗБ')),
            ],
            options={
                'verbose_name': 'О Себе',
                'verbose_name_plural': 'О Себе',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ru', models.CharField(max_length=255, verbose_name='Должность РУС')),
                ('post_uz', models.CharField(max_length=255, verbose_name='Должность УЗБ')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Польное имя РУС')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Польное имя УЗБ')),
                ('work_time_ru', ckeditor.fields.RichTextField(verbose_name='Время работы РУС')),
                ('work_time_uz', ckeditor.fields.RichTextField(verbose_name='Время работы УЗБ')),
                ('contact', models.CharField(max_length=20, verbose_name='Личный тел')),
                ('work_contact', models.CharField(max_length=20, verbose_name='Гос тел')),
                ('photo', models.ImageField(blank=True, upload_to='guide/', verbose_name='Фото')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='Об управлени РУС')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='Об управлени УЗБ')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Управление',
                'verbose_name_plural': 'Управления',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Наименование УЗБ')),
                ('title_ru', models.CharField(max_length=150, verbose_name='Наименование РУС')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='Текст РУС')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='Текст УЗБ')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=250, verbose_name='Организация РУС')),
                ('title_uz', models.CharField(max_length=250, verbose_name='Организация УЗБ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Наименование УЗБ')),
                ('title_ru', models.CharField(max_length=150, verbose_name='Наименование РУС')),
                ('numbers', ckeditor.fields.RichTextField(verbose_name='Телефоны')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Региональное учреждение',
                'verbose_name_plural': 'Региональные учреждения',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ru', models.CharField(max_length=250, verbose_name='Должность РУС')),
                ('post_uz', models.CharField(max_length=250, verbose_name='Должность УЗБ')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Польное имя РУС')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Польное имя УЗБ')),
                ('photo', models.ImageField(blank=True, upload_to='directors/', verbose_name='Фото')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='Текст РУС')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='Текст УЗБ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директоры',
            },
        ),
    ]
