# Generated by Django 4.1.7 on 2023-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Наименование РУС')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Наименование УЗБ')),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='PDF РУС')),
                ('pdf_uz', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='PDF УЗБ')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
        ),
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Наименование РУС')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Наименование УЗБ')),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='open_data/', verbose_name='PDF РУС')),
                ('pdf_uz', models.FileField(blank=True, null=True, upload_to='open_data/', verbose_name='PDF УЗБ')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
        ),
    ]
