# Generated by Django 4.1.7 on 2023-03-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0002_documents_opendata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='opendata',
            options={'verbose_name': 'Открытые данные', 'verbose_name_plural': 'Открытые данные'},
        ),
        migrations.AddField(
            model_name='regional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
    ]
